name=HLG3 HDR
author=Lutaro
tags=HDR, HLG
notes=HLG3 gamma paired with the BT.2020 color mode for direct-to-display HDR.
gamma=HLG3
black_level=0
black_gamma_range=Middle
black_gamma_level=0
knee_mode=Auto
knee_auto_max_point=100%
knee_auto_sensitivity=Mid
color_mode=BT.2020
saturation=0
color_phase=0
color_depth_red=0
color_depth_green=0
color_depth_blue=0
color_depth_cyan=0
color_depth_magenta=0
color_depth_yellow=0
detail_level=0
detail_adjust_mode=Auto
