name=S-Cinetone Look
author=Lutaro
tags=Cinematic
notes=Sony's cinematic gamma and color mode, all other adjustments left at their defaults.
gamma=S-Cinetone
black_level=0
black_gamma_range=Wide
black_gamma_level=0
knee_mode=Auto
knee_auto_max_point=100%
knee_auto_sensitivity=Mid
color_mode=S-Cinetone
saturation=0
color_phase=0
color_depth_red=0
color_depth_green=0
color_depth_blue=0
color_depth_cyan=0
color_depth_magenta=0
color_depth_yellow=0
detail_level=0
detail_adjust_mode=Auto
